### ISSUE TITLE
QuickStart app doesn't work on Internet Explorer 11

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/marklogic-data-hub#463] opened 2017-07-21 14:38 UTC
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

What behavior are you expecting?

#### Tech details

Which Operating System are you using?
DHF and ML deployed on Windows 2012 Server, accessing the Quick Start app from a Windows laptop

Which version of MarkLogic are you using?
9.0-1.1

Which version of the Data Hub Framework are you using?
v2 Beta 1

Is this a QuickStart UI bug? If so, which browser are you using?
IE 11 on a windows laptop

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment] 2017-07-21 18:08
duplicate of #456

**Closed by paxtonhare** 2017-07-21 18:08 UTC
Labels: Component:QuickStart
