### ISSUE TITLE
Error on Harmonize batch on a F5 LB

### ISSUE THREAD

**Issue by ltnd** [marklogic-community/marklogic-data-hub#632] opened 2017-12-21 00:22 UTC
When trying to launch an harmonize task on a F5 load balancer,  we have the following error : 

```
2017-12-19 11:01:20,563 INFO [main] f.k.mbc.harmonize.HarmonizeTasklet [HarmonizeTasklet.java:47]: EnvironmentName : ssl
2017-12-19 11:01:20,629 INFO [main] f.k.mbc.harmonize.HarmonizeTasklet [HarmonizeTasklet.java:60]: Host ppr-marklogic-staging.kkkkkk.fr, stagingPort 443
2017-12-19 11:01:21,582 ERROR [main] o.s.batch.core.step.AbstractStep [AbstractStep.java:229]: Encountered an error executing step harmonizeContratPartStep in job harmonizeJob
com.marklogic.client.MarkLogicIOException: java.io.IOException: unexpected end of stream on Connection{ppr-marklogic-staging.kkkkkk.fr:443, proxy=DIRECT hostAddress=ppr-marklogic-staging.kkkkkk.fr/172.168.0.1:443 cipherSuite=none protocol=http/1.1}
at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:676)
at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:669)
at com.marklogic.client.impl.OkHttpServices.doGet(OkHttpServices.java:3905)
at com.marklogic.client.impl.OkHttpServices.access$1300(OkHttpServices.java:164)
at com.marklogic.client.impl.OkHttpServices$20.apply(OkHttpServices.java:3031)
at com.marklogic.client.impl.OkHttpServices$20.apply(OkHttpServices.java:3029)
at com.marklogic.client.impl.OkHttpServices.sendRequestWithRetry(OkHttpServices.java:698)
at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3034)
at com.marklogic.client.impl.OkHttpServices.getIteratedResource(OkHttpServices.java:3013)
at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)
at com.marklogic.hub.FlowManager.getFlow(FlowManager.java:232)
at fr.kkkkkk.mbc.harmonize.HarmonizeTasklet.execute(HarmonizeTasklet.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
at com.sun.proxy.$Proxy6.execute(Unknown Source)
at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:128)
at org.springframework.batch.core.launch.support.CommandLineJobRunner.start(CommandLineJobRunner.java:362)
at org.springframework.batch.core.launch.support.CommandLineJobRunner.main(CommandLineJobRunner.java:592)
Caused by: java.io.IOException: unexpected end of stream on Connection{ppr-marklogic-staging.kkkkkk.fr:443, proxy=DIRECT hostAddress=ppr-marklogic-staging.kkkkkk.fr/172.168.0.1:443 cipherSuite=none protocol=http/1.1}
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at com.marklogic.client.impl.HTTPBasicAuthInterceptor.intercept(HTTPBasicAuthInterceptor.java:31)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
at okhttp3.RealCall.execute(RealCall.java:69)
at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:674)
... 46 common frames omitted
Caused by: java.io.EOFException: \n not found: limit=0 content=…
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
... 65 common frames omitted
```

A test using directly the JAVA API to execute the following request works : 
"GET /v1/resources/flow?rs:flow-name=HarmonizeContratXQY&rs:flow-type=harmonize&rs:entity-name=Contrat&database=MBC-STAGING HTTP/1.1" 200 443 - "okhttp/3.8.1"

**Comment by damonfeldman** [comment] 2017-12-21 19:55
Does this happen consistently? It is odd that the Java API is in this stack trace, but fails otherwise.

at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)
at com.marklogic.hub.FlowManager.getFlow(FlowManager.java:232)

It may be that the F5 is closing the connection or not dealing with the traffic properly, perhaps intermittently. Another test would be to import the data hub jar and call the FlowManager method directly. Also to try directly against one ML node, bypassing the F5.

**Comment by ltnd** [comment] 2017-12-21 20:14
Yes, it's happening all the time.
It works when we call directly one node, we will try by doing a custom client on the task.

**Comment by damonfeldman** [comment] 2017-12-23 16:23
So if it works directly to one node, I think it is an F5 issue. I will follow up in the ML support ticket.

**Comment by ltnd** [comment] 2017-12-26 13:39
It fails also on 1 node : 
On dhf 2.0.2, the collector is not sent anymore with MarklogicXCC but with okHTTP, which ends with java heap space error.
**AccessLog in DHF 2.0.0 :**
```
127.0.0.1 - mbc_batch_user [26/Dec/2017:02:20:08 +0100] "POST /invoke HTTP/1.1" 200 - - "Java/1.8.0_45 MarkLogicXCC/9.0-3"
```
**AccessLog in DHF 2.0.2 :**
```
127.0.0.1 - mbc_batch_user [26/Dec/2017:02:26:31 +0100] "POST /v1/invoke?database=MBC-STAGING HTTP/1.1" 200 - - "okhttp/3.8.1"
```
We based our code on the description Running Harmonize Flows in https://github.com/marklogic-community/marklogic-data-hub/wiki/Advanced-Hub-Usage#1-use-the-marklogic-data-hub-jar

**Comment by sammefford** [comment] 2017-12-27 15:49
We have seen EOFException from OkHttp before [here](https://github.com/marklogic/java-client-api/issues/814).  I don't know if it's related.  We were seeing it when a node was shut down.  I believe the HTTP response was either blank or prematurely truncated.  With OkHttp we got this EOFException. 
 With Jersey (our outdated HTTP library) we got some child of a SocketException or ConnectionException.  I'll see if I can dig in and find anything from our fix that could be applied to your situation.

**Comment by paxtonhare** [comment] 2018-01-11 20:24
I tested @ltnd 's config against an haproxy load balancer and could not reproduce the issue.

**Comment by aebadirad** [comment] 2018-01-17 19:24
@ltnd Based upon support's feedback and your own investigations, can this issue be closed out without further action?

**Comment by ltnd** [comment] 2018-01-17 22:00
Yes, as DHF uses DMSDK to spread the flows on all servers, it's not really necessary to use a load balancer. (https://docs.marklogic.com/guide/java/data-movement#id_15338 )

**Closed** 2018-01-17 22:00 UTC
