### ISSUE TITLE
Hub (un)install time on windows is horrible

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#253] opened 2016-08-12 19:49 UTC
not sure why

┆Status: To Do

**Comment by popzip** [comment] 2017-12-18 22:27
@paxtonhare do you think still relevant? is it a bug?

**Comment by popzip** [comment] 2018-03-13 02:59
@dmcassel you were using windows, right? Any signs that it is significantly worse than other OS?

**Comment by popzip** [comment] 2018-04-03 20:31
@srinathgit i cannot assign to you, can you check on why?

also can you confirm whether this scenario - uninstall on windows - is in regression?

**Comment by srinathgit** [comment] 2018-04-03 21:07
I am not sure why you can't assign the case to me. The tests (install and uninstall dhf) are running on Windows in Jenkins

**Comment by popzip** [comment] 2018-04-03 21:18
Going to close since this is on an old version. If other performance/time issues please open new ticket.

**Closed** 2018-04-04 15:19 UTC
Labels: Component:QuickStart, bug
